### PR TITLE
[WIP] Add support for custom labels

### PR DESCRIPTION
**Pull request by cryptobioz**

### CODE REVIEW

**Comment by cburki** [comment]
Looks good for me. How do we specify labels in facts ? In role_role ?

**Comment by mcanevet** [comment]
@cburki we were thinking about another way to do it.
The idea would be to have the information in the fact so that we set it for each target. For example:
```yaml
prometheus_exporters:
  collectd:
    - url: http://foo.example.com:9103/metrics
      labels:
        role: myrole
        line: production
```
with this puppet code:
```puppet
concat::fragment {'prometheus_exporter_collectd':
  target  => '/etc/puppetlabs/facter/facts.d/prometheus_exporters.yaml',
  content => @("END")
  collectd:
    - url: http://${::fqdn}:9103/metrics
      labels:
        role: ${::role}
        line: ${::line}
END
  ,
}
```
This would be way more flexible as it would allow to set different labels per target and the prometheus-puppetdb code would be more simple.

**Comment by cburki** [comment]
@mcanevet Thanks for the explanation, that's what I missed. This make sense and I totally agree with that.  I think we could add labels not only for `collectd` targets but also for others like `blackbox`, etc

**Review by cburki — APPROVED** [review]

**Comment by mcanevet** [comment]
Yes sure

**Review by mcanevet — CHANGES_REQUESTED** [review]
Would it be technically possible to implement what we discussed?

**Review by mcanevet — APPROVED** [review]

**Pull request merged**
