### PR TITLE
[WIP] Dynamic targets configuration using Puppet role mapping

### PR DESCRIPTION
**Pull request by dannyk81**
@raphink this is kind of Prototype for #5, it's still WIP but it does work and perhaps a good point to start a discussion before moving forward.

In order to simplify things (for me...) I removed/changed several things:
1. Overrides, not sure if this is needed as the same can be applied on an Exporter level in the role mapping yaml, do we still need to be able to override these things (`metrics_path` & `scheme`) on a target level?

2. Prometheus Scrape Config, as discussed in #7, Prometheus doesn't support "including" configuration files into the main configuration file, so a generic scrape config should be defined instead with a `relabel_configs` to manage the `metrics_path` & `scheme`:
```
  - job_name: 'prometheus-puppetdb'
    file_sd_configs:
      - files:
        - targets.yaml
    relabel_configs:
    - source_labels: [metrics_path]
      regex: (.+)
      action: replace
      target_label: __metrics_path__
    - source_labels: [scheme]
      regex: (.+)
      action: replace
      target_label: __scheme__
    - source_labels: [certname]
      regex: (.+?)\.(.+)
      action: replace
      target_label: instance
      replacement: ${1}
    - regex: ^metrics_path$|^scheme$
      action: labeldrop
```

3. I also split the `puppetdb-query` into Query and Filter, this is needed for us to inject some filters to narrow down the nodes we wish to build the configuration for.

Sorry for breaking a lot of your things 😬

### CODE REVIEW

**Comment by dannyk81** [comment]
@raphink just wondering you had a chance to look at this?

I've been running this for few days nows in two of our deployments and seems to be working well.

**Comment by raphink** [comment]
Not yet. I'll be at work tomorrow and I'll try to look at it. @mcanevet do you have an opinion?

**Comment by mcanevet** [comment]
@dannyk81 thanks for this PR. Unfortunately I'll not ave time to review such a big PR these days. Could you please split it in multiple PR, for example you could start with your changes in the logging system so that the more complicated stuffs are in a smaller PR.

**Comment by dannyk81** [comment]
Thanks for the feedback @mcanevet 

I wanted to break it up initially, but as I started working on this I couldn't decouple the changes, since the change is quite fundamental and touches (almost) everything.

Indeed I could do a separate PR for just the logging & signal handling foundation, but the rest I'm affraid is quite intertwined.

I realize this is a heavy change, but besides the code change, I'm proposing a conceptual change in terms of how this tool works - do you think this is an approach you would like to embrace?

**Comment by mcanevet** [comment]
@dannyk81 wouldn't it be possible to expose exporter ports using a fact so that we don't depend on an external configuration file in yaml?

**Comment by dannyk81** [comment]
@mcanevet the role of the yaml file is to define the relationship between the exporters that are being scraped (i.e. Prometheus jobs) and the corresponding puppet roles where they are running.

It seemed natural to me to include the exporter parameters there as well (i.e. port, metrics_path, scheme, etc...).

I was considering how to represent the same relationship that is defined in this configuration file directly in Puppet (i.e. via facts?) but couldn't arrive at a better solution.

I kind of like the simplicty of the approach, as the configuration file is very readable and all the relationships and parameters are in one place, we manage this file as a template in Puppet and deploy it to the prometheus nodes.

**Comment by mcanevet** [comment]
Wouldn't it be possible to have a structured fact like this:
```
prometheus_exporters=[
  { name = "foo", port = "9101", path = "/foo"},
  { name = "bar", port = "9102" }
]
```
And then adapt this project to look at this fact?
I'd prefer to have this information located in facts so that we can maybe use it for another purpose than having it in a yaml file only available for this project.

**Comment by dannyk81** [comment]
Thanks @mcanevet, this will provide the necessary exporter details, but how about the mapping between exporter(s) and role(s)?

Also, I may lack some Puppet/Facts knowledge, but how should this (custom?) fact be defined in Puppet? I guess through a custom module?

I could see the point behind your reasoning, on the other hand, using a configuration file to manage this means that this solution can be deployed in any common Puppet managed environment without "touching" Puppet itself, the Query & Filter values may be adjusted if there's a need and it should just work.

wdyt?

**Comment by mcanevet** [comment]
@dannyk81 since `v0.7.0` prometheus-puppetdb has been massively rewritten and I think it can now fit your use case (multiple exporter per node). Please read the doc to see how to use it.

**Pull request closed without merging**
